name: YouTube MP3 Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "YouTube URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install -U yt-dlp

      - name: Download MP3
        run: |
          mkdir -p music

          yt-dlp \
          -x \
          --audio-format mp3 \
          --audio-quality 0 \
          --restrict-filenames \
          -o "music/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

          ls -lh music

      - name: Push file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add music/*
          git commit -m "add mp3" || echo "nothing to commit"
          git push
