name: YouTube MP3 Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "YouTube URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ffmpeg + yt-dlp
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          python3 -m pip install -U yt-dlp

      - name: Create downloads folder
        run: mkdir -p downloads

      - name: Download MP3
        run: |
          yt-dlp \
          -x \
          --audio-format mp3 \
          --audio-quality 0 \
          --restrict-filenames \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Show files
        run: |
          ls -lah downloads

      - name: Upload MP3
        uses: actions/upload-artifact@v4
        with:
          name: youtube-mp3
          path: downloads/

