name: YouTube MP3

on:
  workflow_dispatch:
    inputs:
      url:
        description: "YouTube URL"
        required: true

jobs:
  mp3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install yt-dlp

      - name: Download audio
        run: |
          mkdir -p downloads

          yt-dlp \
          --extract-audio \
          --audio-format mp3 \
          --audio-quality 0 \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

          echo "FILES:"
          ls -lah downloads

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mp3
          path: downloads/*
