name: Instagram Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Instagram URL"
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          python3 -m pip install -U yt-dlp

      - name: Create folder
        run: mkdir -p downloads

      - name: Test yt-dlp
        run: |
          yt-dlp --version

      - name: Download Instagram
        run: |
          yt-dlp -v \
          --no-playlist \
          --restrict-filenames \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Check files
        run: |
          echo "FILES:"
          find downloads

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: instagram-download
          path: downloads
